export const auctionColumns = [
  {
    key: 'product.title',
    label: 'Item',
    imageKey: 'product.thumbnail',
    isCheckbox: false,
    isImage: true,
    width: '200',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  { key: 'product.superType', label: 'Collection', sortable: false, width: '100', textAlign: 'start', isDate: false },
  { key: 'price', label: 'Price', sortable: true, width: '100', colorKey: true, textAlign: 'end', isDate: false },
  { key: 'product.rarity', label: 'Rarity', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'lastSalePrice', label: 'Last sale', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'owners', label: 'Owners', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'listingPrice', label: 'Listings', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'createdAt', label: 'Date', sortable: false, width: '150', textAlign: 'center', isDate: true },
]

//  ******  this column for Explore Collection
export const collectionColumns = [
  {
    key: 'isChecked',
    label: 'Select',
    isCheckbox: true,
    isImage: true,
    width: '50',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  {
    key: 'title',
    label: 'Item',
    isCheckbox: false,
    isImage: true,
    width: '200',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  { key: 'superType', label: 'Collection', sortable: false, width: '100', textAlign: 'start', isDate: false },
  {
    key: 'floorPrice',
    label: 'Price',
    sortable: true,
    width: '100',
    colorKey: true,
    textAlign: 'end',
    isDate: false,
  },
  { key: 'rarity', label: 'Rarity', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'listings', label: 'Last sale', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'owners', label: 'Owners', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'listings', label: 'Listings', sortable: false, width: '150', textAlign: 'end', isDate: false },
  { key: 'createdAt', label: 'Date', sortable: false, width: '150', textAlign: 'center', isDate: true },
]

export const PortfolioItemColumns = [
  {
    key: 'isChecked',
    label: 'Select',
    isCheckbox: true,
    isImage: false,
    width: '50',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  {
    key: 'title',
    label: 'Item',
    isCheckbox: false,
    isImage: true,
    width: '200',
    imageKey: 'thumbnail',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  { key: 'superType', label: 'Collection', sortable: false, width: '100', textAlign: 'start', isDate: false },
  {
    key: 'floorPrice',
    label: 'Price',
    sortable: true,
    width: '100',
    colorKey: true,
    textAlign: 'end',
    isDate: false,
  },
  { key: 'rarity', label: 'Rarity', sortable: false, width: '100', textAlign: 'end', isDate: false },
  { key: 'listSale', label: 'Last sale', sortable: false, width: '100', textAlign: 'end', isDate: true },
  { key: 'owners', label: 'Owners', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'listings', label: 'Listings', sortable: false, width: '150', textAlign: 'end', isDate: false },
  { key: 'createdAt', label: 'Date', sortable: false, width: '150', textAlign: 'center', isDate: true },
]

export const TopCollectionColumns = [
  {
    key: 'collectionName',
    label: 'Item',
    imageKey: 'collectionimage',
    isCheckbox: false,
    isImage: true,
    width: '200',
    sortable: false,
    textAlign: 'start',
    isDate: false,
  },
  { key: 'category', label: 'Collection', sortable: true, width: '100', textAlign: 'start', isDate: false },
  { key: 'floorPrice', label: 'Floor', sortable: true, width: '100', colorKey: true, textAlign: 'end', isDate: false },
  { key: 'totalSales', label: 'Sales', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'salesVolume', label: 'Sales Change', sortable: true, width: '130', textAlign: 'end', isDate: false },
  { key: 'volume', label: 'Volume', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'volumeChange', label: 'Volume Change', sortable: true, width: '150', textAlign: 'end', isDate: false },
  { key: 'owner', label: 'Owners', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'supply', label: 'Supply', sortable: true, width: '100', textAlign: 'end', isDate: false },
  { key: 'topBid', label: 'Top Bid', sortable: true, width: '130', textAlign: 'center', isDate: false },
]
